// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package azkeys

import (
	"context"
	"errors"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
)

type DeletedKey struct {
}

type DeleteOperation struct {
	done bool
	id   string
	resp *azcore.Response
}

// Done returns true if the LRO has completed.
func (op *DeleteOperation) Done() bool {
	return op.done
}

// ID returns a value representing the operation that can be used to poll for the status
// of the LRO.  IDs are generated by the service and are unique for the operation.
func (op *DeleteOperation) ID() string {
	return op.id
}

// RegisterProgressReporting registers a callback to be invoked with the progress message.
// The message and interval are determined by the service.
func (op *DeleteOperation) RegisterProgressReporting(report func(string)) {
	// ...
}

// Response returns the last response from the service.
func (op *DeleteOperation) Response() *azcore.Response {
	return op.resp
}

// Poll fetches the latest state of the LRO.
// If Poll fails, the DeleteOperation is unmodified and the error is returned.
// If Poll succeeds and the operation has completed with failure, the DeleteOperation
// is updated and the error is returned.
// If Poll succeeds and the operation has completed successfully, the DeleteOperation
// is updated and the DeletedKey is returned.
// If Poll succeeds and the operation has not completed, the DeleteOperation is
// updated and both return values are nil.
func (op *DeleteOperation) Poll(ctx context.Context) (*DeletedKey, error) {
	return nil, errors.New("TODO")
}

// Wait blocks until the LRO is completed, returning the response or any errors encountered.
// The specified polling interval is used if the server does not return a preferred interval.
func (op *DeleteOperation) Wait(ctx context.Context, pollingInterval time.Duration) (*DeletedKey, error) {
	for {
		dk, err := op.Poll(ctx)
		if err != nil {
			return nil, err
		}
		if op.done {
			return dk, err
		}
		delay := pollingInterval
		if ra, ok := op.resp.RetryAfter(); ok {
			delay = ra
		}
		select {
		case <-time.After(delay):
			// no-op
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	}
}
