// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package cmd

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/Azure/azure-sdk-for-go/sdk/tools/profileBuilder/model"
	"github.com/spf13/cobra"
)

const (
	inputLongName    = "input"
	inputShortName   = "i"
	inputDescription = "Specify the input JSON file to read for the list of modules."
)

// listCmd represents the list command
var listCmd = &cobra.Command{
	Use:   "list",
	Short: "Creates a profile from a set of modules.",
	Long: `Reads a list of modules from the specified JSON file.
Each module will be will be aliased in its own subdirectory under the specified output location.
`,
	Args: cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		if !filepath.IsAbs(outDir) {
			abs, err := filepath.Abs(outDir)
			if err != nil {
				log.Fatalf("failed to convert '%s' to absolute path: %v", outDir, err)
			}
			outDir = abs
		}

		inputFile, err := cmd.Flags().GetString(inputLongName)
		if err != nil {
			log.Fatalf("failed to get %s: %v", inputLongName, err)
		}

		data, err := ioutil.ReadFile(inputFile)
		if err != nil {
			log.Fatalf("failed to read list definition: %v", err)
		}

		var listDef model.ListDefinition
		err = json.Unmarshal(data, &listDef)
		if err != nil {
			log.Fatalf("failed to unmarshal list definition: %v", err)
		}

		fmt.Printf("Executes profileBuilder in %s\n", outDir)
		log.Printf("Output-Location set to: %s", outDir)
		if clearOutdirFlag {
			if err := clearOutputFolder(outDir); err != nil {
				log.Fatalf("Unable to clear output-folder: %v", err)
			}
			generateGoMod(outDir, listDef.Module)
		}
		// go get each module
		for _, mod := range listDef.Require {
			get := "get"
			path := mod.Path
			if updateModFlag {
				get += " -u"
			} else {
				path += "@" + mod.Version
			}
			cmd := exec.Command("go", get, path)
			cmd.Dir = outDir
			log.Println(cmd.String())
			/*if err := cmd.Run(); err != nil {
				log.Fatalf("command failed: %v", err)
			}*/
		}
		if updateModFlag {
			// TODO: write the udpated versions to the list definition
		}
		model.BuildProfile(listDef.Require, outDir)
	},
}

func init() {
	rootCmd.AddCommand(listCmd)
	listCmd.Flags().StringP(inputLongName, inputShortName, "", inputDescription)
	listCmd.MarkFlagRequired(inputLongName)
}

// creates an empty go.mod for module modName in outDir
func generateGoMod(outDir, modName string) error {
	const gomodFormat = "module %s\n\ngo 1.13\n"
	return ioutil.WriteFile(filepath.Join(outDir, "go.mod"), []byte(fmt.Sprintf("module %s\n\ngo 1.13\n", modName)), 0666)
}

func clearOutputFolder(root string) error {
	// delete go.mod and go.sum files
	if err := os.RemoveAll(filepath.Join(root, "go.mod")); err != nil {
		return fmt.Errorf("failed to delete go.mod: %s", err.Error())
	}
	if err := os.RemoveAll(filepath.Join(root, "go.sum")); err != nil {
		return fmt.Errorf("failed to delete go.sum: %s", err.Error())
	}
	// delete all subdirectories
	children, err := getSubdirs(root)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	for _, child := range children {
		childPath := filepath.Join(root, child)
		if err = os.RemoveAll(childPath); err != nil {
			return err
		}
	}
	return nil
}

// getSubdirs returns all of the subdirectories under current.
// Returns an empty slice if current contains no subdirectories.
func getSubdirs(current string) ([]string, error) {
	children, err := ioutil.ReadDir(current)
	if err != nil {
		return nil, err
	}
	dirs := []string{}
	for _, info := range children {
		if info.IsDir() {
			dirs = append(dirs, info.Name())
		}
	}
	return dirs, nil
}
