// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armsecurity

// ValueType - The value type of the items in the list.
type ValueType string

const (
	// ValueTypeIPCidr - An IP range in CIDR format (e.g. '192.168.0.1/8').
	ValueTypeIPCidr ValueType = "IpCidr"
	// ValueTypeString - Any string value.
	ValueTypeString ValueType = "String"
)

// PossibleValueTypeValues returns the possible values for the ValueType const type.
func PossibleValueTypeValues() []ValueType {
	return []ValueType{
		ValueTypeIPCidr,
		ValueTypeString,
	}
}

// ToPtr() returns a *ValueType pointing to the current value.
func (c ValueType) ToPtr() *ValueType {
	return &c
}
