// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armsecurity

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"reflect"
)

// DeviceSecurityGroupListPager provides iteration over DeviceSecurityGroupList pages.
type DeviceSecurityGroupListPager interface {
	azcore.Pager

	// Page returns the current DeviceSecurityGroupListResponse.
	PageResponse() DeviceSecurityGroupListResponse
}

type deviceSecurityGroupListCreateRequest func(context.Context) (*azcore.Request, error)

type deviceSecurityGroupListHandleError func(*azcore.Response) error

type deviceSecurityGroupListHandleResponse func(*azcore.Response) (DeviceSecurityGroupListResponse, error)

type deviceSecurityGroupListAdvancePage func(context.Context, DeviceSecurityGroupListResponse) (*azcore.Request, error)

type deviceSecurityGroupListPager struct {
	// the pipeline for making the request
	pipeline azcore.Pipeline
	// creates the initial request (non-LRO case)
	requester deviceSecurityGroupListCreateRequest
	// callback for handling response errors
	errorer deviceSecurityGroupListHandleError
	// callback for handling the HTTP response
	responder deviceSecurityGroupListHandleResponse
	// callback for advancing to the next page
	advancer deviceSecurityGroupListAdvancePage
	// contains the current response
	current DeviceSecurityGroupListResponse
	// status codes for successful retrieval
	statusCodes []int
	// any error encountered
	err error
}

func (p *deviceSecurityGroupListPager) Err() error {
	return p.err
}

func (p *deviceSecurityGroupListPager) NextPage(ctx context.Context) bool {
	var req *azcore.Request
	var err error
	if !reflect.ValueOf(p.current).IsZero() {
		if p.current.DeviceSecurityGroupList.NextLink == nil || len(*p.current.DeviceSecurityGroupList.NextLink) == 0 {
			return false
		}
		req, err = p.advancer(ctx, p.current)
	} else {
		req, err = p.requester(ctx)
	}
	if err != nil {
		p.err = err
		return false
	}
	resp, err := p.pipeline.Do(req)
	if err != nil {
		p.err = err
		return false
	}
	if !resp.HasStatusCode(p.statusCodes...) {
		p.err = p.errorer(resp)
		return false
	}
	result, err := p.responder(resp)
	if err != nil {
		p.err = err
		return false
	}
	p.current = result
	return true
}

func (p *deviceSecurityGroupListPager) PageResponse() DeviceSecurityGroupListResponse {
	return p.current
}
