//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azadmin/settings"
	"net/http"
	"net/url"
	"regexp"
)

// Server is a fake server for instances of the settings.Client type.
type Server struct {
	// GetSetting is the fake for method Client.GetSetting
	// HTTP status codes to indicate success: http.StatusOK
	GetSetting func(ctx context.Context, settingName string, options *settings.GetSettingOptions) (resp azfake.Responder[settings.GetSettingResponse], errResp azfake.ErrorResponder)

	// GetSettings is the fake for method Client.GetSettings
	// HTTP status codes to indicate success: http.StatusOK
	GetSettings func(ctx context.Context, options *settings.GetSettingsOptions) (resp azfake.Responder[settings.GetSettingsResponse], errResp azfake.ErrorResponder)

	// UpdateSetting is the fake for method Client.UpdateSetting
	// HTTP status codes to indicate success: http.StatusOK
	UpdateSetting func(ctx context.Context, settingName string, parameters settings.UpdateSettingRequest, options *settings.UpdateSettingOptions) (resp azfake.Responder[settings.UpdateSettingResponse], errResp azfake.ErrorResponder)
}

// NewServerTransport creates a new instance of ServerTransport with the provided implementation.
// The returned ServerTransport instance is connected to an instance of settings.Client via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewServerTransport(srv *Server) *ServerTransport {
	return &ServerTransport{srv: srv}
}

// ServerTransport connects instances of settings.Client to instances of Server.
// Don't use this type directly, use NewServerTransport instead.
type ServerTransport struct {
	srv *Server
}

// Do implements the policy.Transporter interface for ServerTransport.
func (s *ServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	var resp *http.Response
	var err error

	switch method {
	case "Client.GetSetting":
		resp, err = s.dispatchGetSetting(req)
	case "Client.GetSettings":
		resp, err = s.dispatchGetSettings(req)
	case "Client.UpdateSetting":
		resp, err = s.dispatchUpdateSetting(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (s *ServerTransport) dispatchGetSetting(req *http.Request) (*http.Response, error) {
	if s.srv.GetSetting == nil {
		return nil, &nonRetriableError{errors.New("fake for method GetSetting not implemented")}
	}
	const regexStr = `/settings/(?P<setting_name>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 1 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	settingNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("setting_name")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := s.srv.GetSetting(req.Context(), settingNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).Setting, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *ServerTransport) dispatchGetSettings(req *http.Request) (*http.Response, error) {
	if s.srv.GetSettings == nil {
		return nil, &nonRetriableError{errors.New("fake for method GetSettings not implemented")}
	}
	respr, errRespr := s.srv.GetSettings(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).ListResult, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *ServerTransport) dispatchUpdateSetting(req *http.Request) (*http.Response, error) {
	if s.srv.UpdateSetting == nil {
		return nil, &nonRetriableError{errors.New("fake for method UpdateSetting not implemented")}
	}
	const regexStr = `/settings/(?P<setting_name>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 1 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[settings.UpdateSettingRequest](req)
	if err != nil {
		return nil, err
	}
	settingNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("setting_name")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := s.srv.UpdateSetting(req.Context(), settingNameParam, body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).Setting, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
