//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fake

import (
	"encoding/json"
	"net/http"
	"reflect"
)

type nonRetriableError struct {
	error
}

func (nonRetriableError) NonRetriable() {
	// marker method
}

func getOptional[T any](v T) *T {
	if reflect.ValueOf(v).IsZero() {
		return nil
	}
	return &v
}

func parseOptional[T any](v string, parse func(v string) (T, error)) (*T, error) {
	if v == "" {
		return nil, nil
	}
	t, err := parse(v)
	if err != nil {
		return nil, err
	}
	return &t, err
}

func marshalResponseAsJSON(req *http.Request, v any) (*http.Response, error) {
	body, err := json.Marshal(v)
	if err != nil {
		return nil, &nonRetriableError{err}
	}
	resp := newResponse(http.StatusOK, "OK", req, string(body)), nil
	for key := range r.h {
		resp.Header.Set(key, r.h.Get(key))
	}
	return resp, nil
}
