// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package model

import (
	"fmt"
	"go/ast"
	"go/token"
	"sort"
)

const (
	origImportAlias = "original"
)

// NewAliasFile creates an alias file from the specified input package.
func NewAliasFile(original *ast.Package, originalImport string) (*ast.File, error) {
	aliasFile := &ast.File{
		Name: &ast.Ident{
			Name: original.Name,
		},
	}

	aliasFile.Decls = append(aliasFile.Decls, &ast.GenDecl{
		Tok: token.IMPORT,
		Specs: []ast.Spec{
			&ast.ImportSpec{
				Name: &ast.Ident{
					Name: origImportAlias,
				},
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: fmt.Sprintf("\"%s\"", originalImport),
				},
			},
		},
	})

	genDecls := []*ast.GenDecl{}
	funcDecls := []*ast.FuncDecl{}

	// node traversal is non-deterministic so we maintain a collection
	// that allows us to emit the nodes in a sort order of our choice
	ast.Inspect(original, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.FuncDecl:
			// exclude methods as they're exposed on the aliased types
			if node.Recv == nil {
				funcDecls = append(funcDecls, node)
			}
			// return false as we don't care about the function body
			return false
		case *ast.GenDecl:
			genDecls = append(genDecls, node)
		}
		return true
	})

	// genDecls contains constants and type definitions.  group them so that
	// type defs for consts are next to their respective list of constants.

	type constType struct {
		name     string
		typeSpec *ast.GenDecl
		values   *ast.GenDecl
	}

	untypedConsts := []*ast.GenDecl{}
	constTypeMap := map[string]*constType{}

	// first build a map from all the constants
	for _, gd := range genDecls {
		if gd.Tok == token.CONST {
			// get the const type from the first item
			vs := gd.Specs[0].(*ast.ValueSpec)
			if vs.Type == nil {
				// untyped consts go first
				untypedConsts = append(untypedConsts, gd)
				continue
			}
			typeName := vs.Type.(*ast.Ident).Name
			constTypeMap[typeName] = &constType{
				name:   typeName,
				values: gd,
			}
		}
	}

	// now update the map with the type specs
	typeSpecs := []*ast.GenDecl{}
	for _, gd := range genDecls {
		if gd.Tok == token.TYPE {
			spec := gd.Specs[0].(*ast.TypeSpec)
			// check if the typespec is in the map, if it is it's for a constant
			if typeMap, ok := constTypeMap[spec.Name.Name]; ok {
				typeMap.typeSpec = gd
			} else {
				typeSpecs = append(typeSpecs, gd)
			}
		}
	}

	// add consts, types, and funcs, in that order, in sorted order

	// add any untyped consts first
	sort.SliceStable(untypedConsts, func(i, j int) bool {
		tsI := untypedConsts[i].Specs[0].(*ast.TypeSpec)
		tsJ := untypedConsts[j].Specs[0].(*ast.TypeSpec)
		return tsI.Name.Name < tsJ.Name.Name
	})
	for _, uc := range untypedConsts {
		aliasFile.Decls = append(aliasFile.Decls, createAliasConsts(uc))
	}

	// now handle typed const and their values (i.e. enums)
	// convert to slice for sorting
	constDecls := []*constType{}
	for _, v := range constTypeMap {
		constDecls = append(constDecls, v)
	}
	sort.SliceStable(constDecls, func(i, j int) bool {
		return constDecls[i].name < constDecls[j].name
	})
	for _, cd := range constDecls {
		aliasFile.Decls = append(aliasFile.Decls, createAliasType(cd.typeSpec))
		aliasFile.Decls = append(aliasFile.Decls, createAliasConsts(cd.values))
	}

	// now do the typespecs
	sort.SliceStable(typeSpecs, func(i, j int) bool {
		tsI := typeSpecs[i].Specs[0].(*ast.TypeSpec)
		tsJ := typeSpecs[j].Specs[0].(*ast.TypeSpec)
		return tsI.Name.Name < tsJ.Name.Name
	})
	for _, ts := range typeSpecs {
		aliasFile.Decls = append(aliasFile.Decls, createAliasType(ts))
	}

	// finally add the funcs
	sort.SliceStable(funcDecls, func(i, j int) bool {
		return funcDecls[i].Name.Name < funcDecls[j].Name.Name
	})
	for _, fd := range funcDecls {
		aliasFile.Decls = append(aliasFile.Decls, createAliasFunc(fd))
	}

	return aliasFile, nil
}

// creates a const block that aliases the original values
func createAliasConsts(orig *ast.GenDecl) *ast.GenDecl {
	if orig.Tok != token.CONST {
		panic(fmt.Sprintf("expected CONST, got %s", orig.Tok))
	}
	return &ast.GenDecl{
		Doc:   cloneCommentGroup(orig.Doc),
		Tok:   orig.Tok,
		Specs: cloneSpecs(orig.Specs),
	}
}

// create a type alias declaration for the original type
func createAliasType(orig *ast.GenDecl) *ast.GenDecl {
	if orig.Tok != token.TYPE {
		panic(fmt.Sprintf("expected TYPE, got %s", orig.Tok))
	}
	return &ast.GenDecl{
		Doc: cloneCommentGroup(orig.Doc),
		Tok: orig.Tok,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name:   cloneIdent(orig.Specs[0].(*ast.TypeSpec).Name),
				Assign: 1,
				Type: &ast.SelectorExpr{
					X: &ast.Ident{
						Name: origImportAlias,
					},
					Sel: &ast.Ident{
						Name: orig.Specs[0].(*ast.TypeSpec).Name.Name,
					},
				},
			},
		},
	}
}

// creates the alias func from the provided func
func createAliasFunc(orig *ast.FuncDecl) *ast.FuncDecl {
	var arguments []ast.Expr
	if orig.Type.Params != nil {
		arguments = make([]ast.Expr, len(orig.Type.Params.List))
		for i := range orig.Type.Params.List {
			arguments[i] = cloneIdent(orig.Type.Params.List[i].Names[0])
		}
	}
	return &ast.FuncDecl{
		Doc: cloneCommentGroup(orig.Doc),
		Name: &ast.Ident{
			Name: orig.Name.Name,
		},
		Type: cloneFuncType(orig.Type),
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X: &ast.Ident{
									Name: origImportAlias,
								},
								Sel: &ast.Ident{
									Name: orig.Name.Name,
								},
							},
							Args: arguments,
						},
					},
				},
			},
		},
	}
}

// helpers used to create the aliased content

func cloneBasicLit(bl *ast.BasicLit) *ast.BasicLit {
	if bl == nil {
		return nil
	}
	return &ast.BasicLit{
		Kind:  bl.Kind,
		Value: bl.Value,
	}
}

func cloneCommentGroup(cg *ast.CommentGroup) *ast.CommentGroup {
	if cg == nil {
		return nil
	}
	cmts := []*ast.Comment{}
	for _, c := range cg.List {
		cmt := &ast.Comment{
			Text: c.Text,
		}
		cmts = append(cmts, cmt)
	}
	return &ast.CommentGroup{List: cmts}
}

func cloneStarExpr(s *ast.StarExpr) *ast.StarExpr {
	return &ast.StarExpr{
		X: cloneExpr(s.X),
	}
}

func cloneSelectorExpr(s *ast.SelectorExpr) *ast.SelectorExpr {
	return &ast.SelectorExpr{
		X:   cloneExpr(s.X),
		Sel: cloneIdent(s.Sel),
	}
}

func cloneArrayType(at *ast.ArrayType) *ast.ArrayType {
	return &ast.ArrayType{
		Len: cloneExpr(at.Len),
		Elt: cloneExpr(at.Elt),
	}
}

func cloneExpr(exp ast.Expr) ast.Expr {
	if exp == nil {
		return nil
	}
	// expand cases as needed
	switch x := exp.(type) {
	case *ast.Ident:
		return cloneIdent(x)
	case *ast.BasicLit:
		return cloneBasicLit(x)
	case *ast.FuncType:
		return cloneFuncType(x)
	case *ast.StarExpr:
		return cloneStarExpr(x)
	case *ast.SelectorExpr:
		return cloneSelectorExpr(x)
	case *ast.ArrayType:
		return cloneArrayType(x)
	/*case *ast.BadExpr:
		return cloneBadExpr(x)
	case *ast.Ellipsis:
		return cloneEllipsis(x)
	case *ast.FuncLit:
		return cloneFuncLit(x)
	case *ast.CompositeLit:
		return cloneCompositeLit(x)
	case *ast.ParenExpr:
		return cloneParenExpr(x)
	case *ast.IndexExpr:
		return cloneIndexExpr(x)
	case *ast.SliceExpr:
		return cloneSliceExpr(x)
	case *ast.TypeAssertExpr:
		return cloneTypeAssertExpr(x)
	case *ast.CallExpr:
		return cloneCallExpr(x)
	case *ast.StarExpr:
		return cloneStarExpr(x)
	case *ast.UnaryExpr:
		return cloneUnaryExpr(x)
	case *ast.BinaryExpr:
		return cloneBinaryExpr(x)
	case *ast.KeyValueExpr:
		return cloneKeyValueExpr(x)
	case *ast.StructType:
		return cloneStructType(x)
	case *ast.InterfaceType:
		return cloneInterfaceType(x)
	case *ast.MapType:
		return cloneMapType(x)
	case *ast.ChanType:
		return cloneChanType(x)*/
	default:
		panic(fmt.Sprintf("unhandled expression %T", x))
	}
}

func cloneIdents(id []*ast.Ident) []*ast.Ident {
	if id == nil {
		return nil
	}
	ids := []*ast.Ident{}
	for _, i := range id {
		ids = append(ids, cloneIdent(i))
	}
	return ids
}

func cloneIdent(i *ast.Ident) *ast.Ident {
	if i == nil {
		return nil
	}
	return &ast.Ident{
		Name: i.Name,
		// TODO: Obj:  cloneObject(i.Obj),
	}
}

func cloneField(f *ast.Field) *ast.Field {
	if f == nil {
		return nil
	}
	return &ast.Field{
		Doc:     cloneCommentGroup(f.Doc),
		Names:   cloneIdents(f.Names),
		Type:    cloneExpr(f.Type),
		Tag:     cloneBasicLit(f.Tag),
		Comment: cloneCommentGroup(f.Comment),
	}
}

func cloneFieldList(fl *ast.FieldList) *ast.FieldList {
	if fl == nil {
		return nil
	}
	list := []*ast.Field{}
	for _, field := range fl.List {
		list = append(list, cloneField(field))
	}
	return &ast.FieldList{List: list}
}

func cloneFuncType(f *ast.FuncType) *ast.FuncType {
	return &ast.FuncType{
		Params:  cloneFieldList(f.Params),
		Results: cloneFieldList(f.Results),
	}
}

/*func cloneObject(o *ast.Object) *ast.Object {
	if o == nil {
		return nil
	}
	return &ast.Object{
		Kind: o.Kind,
		Name: o.Name,
	}
}*/

func cloneSpecs(specs []ast.Spec) []ast.Spec {
	if specs == nil {
		return nil
	}
	ns := []ast.Spec{}
	for _, spec := range specs {
		vs := spec.(*ast.ValueSpec)
		ns = append(ns, createAliasValueSpec(vs))
	}
	return ns
}

func createAliasValueSpec(vs *ast.ValueSpec) *ast.ValueSpec {
	names := cloneIdents(vs.Names)
	values := []ast.Expr{}
	for _, name := range names {
		values = append(values, &ast.SelectorExpr{
			X: &ast.Ident{
				Name: origImportAlias,
			},
			Sel: &ast.Ident{
				Name: name.Name,
			},
		})
	}
	return &ast.ValueSpec{
		Doc:     cloneCommentGroup(vs.Doc),
		Names:   names,
		Values:  values,
		Comment: cloneCommentGroup(vs.Comment),
	}
}
